### ISSUE TITLE
Issue: Improve Extension Frontend Design

### ISSUE THREAD

**Issue by aditya-8-88** [aditya-8-88/Session-Tracker-Extension#1]
## Description
The current frontend design of the popup is functional but lacks user-friendly aesthetics and modern styling. To enhance the user experience, we should update the design with the following changes:

### 1. Modern UI Design
- Replace the basic HTML structure with a more visually appealing layout.
- Use a modern CSS framework (e.g., Bootstrap or TailwindCSS) for better styling.

### 2. Session List Improvements
- Add timestamps for when each session was saved.
- Allow renaming of sessions directly from the popup.

### 3. Interactive Buttons
- Style the buttons with hover effects and color themes.
- Add icons next to "Save Current Session" and session items.

### 4. Responsive Design
- Ensure the popup scales well across different screen resolutions.

## Tasks
1. Update `popup.html` and `styles.css` to implement the new design.
2. Enhance `popup.js` to support additional interactive features like renaming sessions.
3. Add a small footer or header with the extension name/logo.

## Expected Outcome
A visually appealing and user-friendly interface that improves usability and aligns with modern design practices.

**Comment by Gulin7** [comment]
Hi, @aditya-8-88 , can I take this issue? As well as issue #2

**Comment by aditya-8-88** [comment]
Sure, feel free to take up the issue! Let me know if you have any questions or need assistance while working on it.
